import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import BaseTemplate from "../components/templates/BaseTemplate";
import HeroBanner from "../components/elements/HeroBanner";
import Heading from "../components/elements/Heading";
import FormsModule from "../components/modules/FormsModule";
import FormModel from "../models/FormModel";
import BaseContainer from "../components/layouts/BaseContainer";
import withAuth from "../auth/withAuth";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500&display=swap"
          rel="stylesheet"
        />
      </Head>
      
      <BaseTemplate>
        <HeroBanner imageUrl="/img/hero-banner.jpg" />
    
          <BaseContainer>

            <Heading
              heading="Welcome"
              subheading="Please choose a form from below for your required purpose"
            />
            <FormsModule
              title="Forms"
              formItems={[
                new FormModel(
                  new Date().toISOString(),
                  "Club Registration Form",
                  "/"
                ),
                new FormModel(
                  new Date().toISOString(),
                  "Tournament Registration Form",
                  "/"
                ),
              ]}
            />
          </BaseContainer>
        
      </BaseTemplate>
    
    </>
  );
};

export default Home;
