import MainNavModule from "../modules/MainNavModule";
import Head from "next/head";

const BaseTemplate: React.FC<{}> = (props) => {
  return (
    <>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <MainNavModule />
      <main className="w-screen h-full">{props.children}</main>
    </>
  );
};

export default BaseTemplate;
